### ISSUE TITLE
Logs Folder

### ISSUE THREAD

**Issue by TRiebesel** [haavarstein/Automation-Framework-Community-Edition#1]
Hello,
I use the new Framework Version to deploy a mdt Server. When I run the Script I got the error the C:\Logs folder already existed. On a WS2016 is the C:\Logs Folder the destination for the event logs.

best regards
Tobias

**Comment by haavarstein** [comment]
Hi Tobias, saw the same today. This happens when you deploy on Azure because that folder already exists, will make a check prior. The folder is shared fine though. It’s the Deployment logs which are saved to this folder after a successful deployment.
 
Eric

**Comment by TRiebesel** [comment]
Hello Eric,
I have the on a WS2016 Server clean install from a   Vlsc Image!

Thanks for the quick response!

Tobias

Outlook für iOS<https://aka.ms/o0ukef> beziehen

________________________________
Von: Trond Eirik Haavarstein <notifications@github.com>
Gesendet: Dienstag, November 13, 2018 2:15 PM
An: haavarstein/Automation-Framework-Community-Edition
Cc: Tobias Riebesel; Author
Betreff: Re: [haavarstein/Automation-Framework-Community-Edition] Logs Folder (#1)

Hi Tobias, saw the same today. This happens when you deploy on Azure because that folder already exists, will make a check prior. The folder is shared fine though. It’s the Deployment logs which are saved to this folder after a successful deployment.



Eric

**Comment by haavarstein** [comment]
The issue has been resolved, thanks for the feedback.
